/**
 * Emit Pydantic v2 BaseModel + Enum definitions for a ServiceNow table.
 * Pure function — consumes CodegenData from codegen-fetch.ts.
 */

import { tableToTypeName } from "./sn-types.ts";
import type { CodegenData } from "./codegen-fetch.ts";
import type { DictEntry, ChoiceEntry } from "./codegen-ts.ts";

export interface PythonOptions {
  includeSystem?: boolean;
  skipInactive?: boolean;
}

const SYSTEM_FIELDS = new Set([
  "sys_id", "sys_created_on", "sys_created_by", "sys_updated_on", "sys_updated_by",
  "sys_mod_count", "sys_domain", "sys_domain_path", "sys_tags", "sys_scope",
  "sys_class_name", "sys_overrides", "sys_update_name", "sys_package", "sys_policy",
  "sys_name", "sys_replace_on_upgrade",
]);

const NUMERIC_TYPES = new Set([
  "integer", "decimal", "float", "longint", "longint_number",
  "percent_complete", "order", "duration",
]);
const BOOLEAN_TYPES = new Set(["boolean"]);

function isTruthy(v: unknown): boolean {
  if (typeof v === "boolean") return v;
  if (typeof v === "string") return v === "true" || v === "1";
  return !!v;
}
function isFalsy(v: unknown): boolean {
  if (v === undefined || v === null) return true;
  if (typeof v === "string") return v === "" || v === "false";
  return false;
}

/** `1` → "_1", `P1` → "P_1" (Python identifiers can't start with a digit). */
function toEnumMember(value: string): string {
  // Uppercase, replace non-alphanumerics with _, prefix _ if starts with digit
  let out = value
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
  if (!out) out = "VALUE";
  if (/^[0-9]/.test(out)) out = "_" + out;
  return out;
}

function buildChoiceEnum(
  className: string,
  fieldName: string,
  entries: ChoiceEntry[]
): { code: string; enumName: string } | null {
  const active = entries.filter((e) => !isTruthy(e.inactive));
  if (active.length === 0) return null;
  const enumName = `${className}${toPascalField(fieldName)}`;
  const lines: string[] = [];
  lines.push(`class ${enumName}(str, Enum):`);
  lines.push(`    """Choice values for \`${fieldName}\`."""`);
  const used = new Set<string>();
  for (const e of active) {
    let member = toEnumMember(e.value);
    // Dedup collisions (e.g. if two values normalise to the same)
    let suffix = 1;
    while (used.has(member)) {
      suffix++;
      member = `${toEnumMember(e.value)}_${suffix}`;
    }
    used.add(member);
    lines.push(`    ${member} = ${pyStr(e.value)}  # ${e.label}`);
  }
  return { code: lines.join("\n"), enumName };
}

function toPascalField(field: string): string {
  return field
    .split(/[_-]/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
    .join("");
}

function pyStr(s: string): string {
  // Python string literal; prefer double quotes unless the value has quotes.
  if (!s.includes('"')) return `"${s.replace(/\\/g, "\\\\")}"`;
  if (!s.includes("'")) return `'${s.replace(/\\/g, "\\\\")}'`;
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function mapPythonType(entry: DictEntry): { type: string; note?: string } {
  const t = entry.internal_type;
  if (NUMERIC_TYPES.has(t)) {
    if (t === "float" || t === "decimal") return { type: "float" };
    return { type: "int" };
  }
  if (BOOLEAN_TYPES.has(t)) return { type: "bool" };
  if (t === "glide_date_time" || t === "glide_date" || t === "glide_time" || t === "due_date") {
    return {
      type: "str",
      note: `${t} — ServiceNow datetime format (e.g. "2026-04-20 15:30:00"); not ISO`,
    };
  }
  if (t === "reference" && entry.reference) {
    return { type: "str", note: `References ${entry.reference}.sys_id` };
  }
  return { type: "str" };
}

export function generatePython(data: CodegenData, opts: PythonOptions = {}): string {
  const {
    table,
    tableLabel,
    instanceUrl,
    dictionary,
    choices,
    ancestors,
  } = data;
  const { includeSystem = true, skipInactive = true } = opts;
  const className = tableToTypeName(table);

  const seen = new Set<string>();
  const fields: DictEntry[] = [];
  for (const entry of dictionary) {
    if (!entry.element) continue;
    if (seen.has(entry.element)) continue;
    if (skipInactive && isFalsy(entry.active) && entry.active !== undefined) continue;
    if (!includeSystem && SYSTEM_FIELDS.has(entry.element)) continue;
    seen.add(entry.element);
    fields.push(entry);
  }
  fields.sort((a, b) => a.element.localeCompare(b.element));

  const lines: string[] = [];

  // Header
  lines.push(`"""`);
  lines.push(`Generated by @seemsindie/servicenow-cli — Pydantic models for \`${table}\`.`);
  if (tableLabel) lines.push(`Label:   ${tableLabel}`);
  if (ancestors.length > 1) lines.push(`Extends: ${ancestors.slice(1).join(" → ")}`);
  if (instanceUrl) lines.push(`Source:  ${instanceUrl}`);
  lines.push(``);
  lines.push(`Regenerate: sn codegen python ${table}`);
  lines.push(`"""`);
  lines.push(`from __future__ import annotations`);
  lines.push(``);
  lines.push(`from enum import Enum`);
  lines.push(`from typing import Optional`);
  lines.push(``);
  lines.push(`from pydantic import BaseModel, Field`);
  lines.push(``);
  lines.push(``);

  // Emit choice enums
  const enumByField = new Map<string, string>(); // field name → enum class name
  for (const field of fields) {
    const entries = choices.get(field.element);
    if (!entries || entries.length === 0) continue;
    const built = buildChoiceEnum(className, field.element, entries);
    if (!built) continue;
    enumByField.set(field.element, built.enumName);
    lines.push(built.code);
    lines.push(``);
    lines.push(``);
  }

  // Main BaseModel
  lines.push(`class ${className}(BaseModel):`);
  if (tableLabel) {
    lines.push(`    """${tableLabel} (${table}) record."""`);
  } else {
    lines.push(`    """Record type for SN table \`${table}\`."""`);
  }
  lines.push(``);

  for (const field of fields) {
    const enumName = enumByField.get(field.element);
    const { type: baseType, note } = enumName ? { type: enumName, note: undefined } : mapPythonType(field);
    const mandatory = isTruthy(field.mandatory);

    const descParts: string[] = [];
    if (field.column_label) descParts.push(field.column_label);
    if (note) descParts.push(note);
    if (field.max_length && !enumName && baseType === "str") descParts.push(`Max length: ${field.max_length}`);
    const desc = descParts.join(" · ");

    const typeDecl = mandatory ? baseType : `Optional[${baseType}]`;
    const defaultDecl = mandatory
      ? desc ? ` = Field(..., description=${pyStr(desc)})` : ""
      : desc ? ` = Field(default=None, description=${pyStr(desc)})` : " = None";

    lines.push(`    ${field.element}: ${typeDecl}${defaultDecl}`);
  }

  lines.push(``);
  return lines.join("\n");
}
