/**
 * Emit Go struct + typed string constants for a ServiceNow table.
 * Pure function — consumes CodegenData from codegen-fetch.ts.
 */

import { tableToTypeName } from "./sn-types.ts";
import type { CodegenData } from "./codegen-fetch.ts";
import type { DictEntry, ChoiceEntry } from "./codegen-ts.ts";

export interface GoOptions {
  packageName?: string;
  includeSystem?: boolean;
  skipInactive?: boolean;
}

const SYSTEM_FIELDS = new Set([
  "sys_id", "sys_created_on", "sys_created_by", "sys_updated_on", "sys_updated_by",
  "sys_mod_count", "sys_domain", "sys_domain_path", "sys_tags", "sys_scope",
  "sys_class_name", "sys_overrides", "sys_update_name", "sys_package", "sys_policy",
  "sys_name", "sys_replace_on_upgrade",
]);

const NUMERIC_INT = new Set(["integer", "longint", "longint_number", "percent_complete", "order", "duration"]);
const NUMERIC_FLOAT = new Set(["decimal", "float"]);

/**
 * Acronyms Go linters (golint/revive) expect fully uppercased in identifiers.
 * sys_id → SysID, http_url → HTTPURL, user_api_key → UserAPIKey.
 */
const GO_ACRONYMS = new Set([
  "ID", "URL", "URI", "IP", "HTTP", "HTTPS", "JSON", "XML", "HTML", "CSS",
  "SSH", "SQL", "API", "REST", "DNS", "CPU", "RAM", "GPU", "UID", "GUID",
  "UUID", "SLA", "UI", "TTL", "MIME", "TLS", "ACL",
]);

function isTruthy(v: unknown): boolean {
  if (typeof v === "boolean") return v;
  if (typeof v === "string") return v === "true" || v === "1";
  return !!v;
}
function isFalsy(v: unknown): boolean {
  if (v === undefined || v === null) return true;
  if (typeof v === "string") return v === "" || v === "false";
  return false;
}

/**
 * Convert snake_case to PascalCase with acronym preservation.
 *   sys_id      → SysID
 *   http_url    → HTTPURL
 *   assigned_to → AssignedTo
 */
export function snakeToPascal(s: string): string {
  return s
    .split(/[_-]+/)
    .filter(Boolean)
    .map((part) => {
      const upper = part.toUpperCase();
      if (GO_ACRONYMS.has(upper)) return upper;
      return part.charAt(0).toUpperCase() + part.slice(1).toLowerCase();
    })
    .join("");
}

/** Value → Go const member name. "1" → "1" (will be prefixed with type name). */
function valueToConstSuffix(value: string, label: string): string {
  // Prefer label for readability if it makes a clean identifier
  const candidate = label || value;
  let suffix = candidate
    .replace(/[^A-Za-z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((w) => {
      const upper = w.toUpperCase();
      if (GO_ACRONYMS.has(upper)) return upper;
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    })
    .join("");
  if (!suffix) suffix = "Value";
  if (/^[0-9]/.test(suffix)) suffix = "V" + suffix;
  return suffix;
}

function mapGoType(entry: DictEntry): { type: string; note?: string } {
  const t = entry.internal_type;
  if (NUMERIC_INT.has(t)) return { type: "int64" };
  if (NUMERIC_FLOAT.has(t)) return { type: "float64" };
  if (t === "boolean") return { type: "bool" };
  if (t === "glide_date_time" || t === "glide_date" || t === "glide_time" || t === "due_date") {
    return {
      type: "string",
      note: `${t} — ServiceNow datetime format; not RFC3339`,
    };
  }
  if (t === "reference" && entry.reference) {
    return { type: "string", note: `References ${entry.reference}.sys_id` };
  }
  return { type: "string" };
}

export function generateGo(data: CodegenData, opts: GoOptions = {}): string {
  const {
    table,
    tableLabel,
    instanceUrl,
    dictionary,
    choices,
    ancestors,
  } = data;
  const {
    packageName = "servicenow",
    includeSystem = true,
    skipInactive = true,
  } = opts;

  const structName = tableToTypeName(table);

  const seen = new Set<string>();
  const fields: DictEntry[] = [];
  for (const entry of dictionary) {
    if (!entry.element) continue;
    if (seen.has(entry.element)) continue;
    if (skipInactive && isFalsy(entry.active) && entry.active !== undefined) continue;
    if (!includeSystem && SYSTEM_FIELDS.has(entry.element)) continue;
    seen.add(entry.element);
    fields.push(entry);
  }
  fields.sort((a, b) => a.element.localeCompare(b.element));

  const lines: string[] = [];

  // File header
  lines.push(`// Code generated by @seemsindie/servicenow-cli. DO NOT EDIT.`);
  lines.push(`// Regenerate with: sn codegen go ${table}`);
  lines.push(`//`);
  if (tableLabel) lines.push(`// Label:   ${tableLabel}`);
  if (ancestors.length > 1) lines.push(`// Extends: ${ancestors.slice(1).join(" -> ")}`);
  if (instanceUrl) lines.push(`// Source:  ${instanceUrl}`);
  lines.push(``);
  lines.push(`package ${packageName}`);
  lines.push(``);

  // Choice types + const blocks
  const typeByField = new Map<string, string>(); // field name → Go type name (for choice fields)
  for (const field of fields) {
    const entries = choices.get(field.element);
    if (!entries || entries.length === 0) continue;
    const active = entries.filter((c) => !isTruthy(c.inactive));
    if (active.length === 0) continue;

    const typeName = `${structName}${snakeToPascal(field.element)}`;
    typeByField.set(field.element, typeName);

    lines.push(`// ${typeName} enumerates choice values for ${table}.${field.element}.`);
    lines.push(`type ${typeName} string`);
    lines.push(``);
    lines.push(`const (`);
    const used = new Set<string>();
    for (const c of active) {
      let memberName = `${typeName}${valueToConstSuffix(c.value, c.label)}`;
      let suffix = 1;
      while (used.has(memberName)) {
        suffix++;
        memberName = `${typeName}${valueToConstSuffix(c.value, c.label)}${suffix}`;
      }
      used.add(memberName);
      const strVal = goStringLit(c.value);
      lines.push(`\t${memberName} ${typeName} = ${strVal} // ${c.label}`);
    }
    lines.push(`)`);
    lines.push(``);
  }

  // Main struct
  lines.push(`// ${structName} represents a ServiceNow \`${table}\` record.`);
  if (tableLabel) lines.push(`// Label: ${tableLabel}`);
  lines.push(`type ${structName} struct {`);
  for (const field of fields) {
    const choiceType = typeByField.get(field.element);
    const { type: baseType, note } = choiceType
      ? { type: choiceType, note: undefined }
      : mapGoType(field);

    const comments: string[] = [];
    if (field.column_label) comments.push(field.column_label);
    if (note) comments.push(note);
    if (field.max_length && baseType === "string" && !choiceType) {
      comments.push(`Max length: ${field.max_length}`);
    }
    if (comments.length > 0) {
      lines.push(`\t// ${comments.join(" · ")}`);
    }

    const goFieldName = snakeToPascal(field.element);
    const tag = `\`json:"${field.element}"\``;
    lines.push(`\t${goFieldName} ${baseType} ${tag}`);
    lines.push(``);
  }
  // Strip trailing blank line inside struct
  if (lines[lines.length - 1] === "") lines.pop();
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}

function goStringLit(s: string): string {
  // Plain Go string — escape quotes and backslashes.
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
