/**
 * Parser + Zod schema for `sn record-producer create -f spec.yaml`.
 *
 * Scaffolds a Record Producer in SN:
 *   sys_cat_item_producer  — the catalog item that creates target records
 *   item_option_new (xN)   — one per variable (the form fields)
 *   question_choice (xM)   — choice values for choice-type variables
 */

import { parse as parseYaml } from "yaml";
import { z } from "zod";
import { readFileSync } from "fs";

/** SN's internal type codes for variables (item_option_new.type). */
const VARIABLE_TYPES = {
  string: 6,
  multi_line_text: 2,
  choice: 5,
  boolean: 7,
  reference: 8,
  date: 9,
  date_time: 10,
  integer: 16,
} as const;

export type VariableTypeName = keyof typeof VARIABLE_TYPES;

const VariableSchema = z
  .object({
    name: z
      .string()
      .min(1)
      .regex(
        /^[a-z][a-z0-9_]*$/,
        "variable names must be lowercase with underscores"
      ),
    label: z.string().min(1),
    type: z.enum(
      Object.keys(VARIABLE_TYPES) as [VariableTypeName, ...VariableTypeName[]]
    ),
    mandatory: z.boolean().default(false),
    default_value: z.string().optional(),
    help_text: z.string().optional(),
    /** For type=choice. Each string becomes a question_choice row. */
    choices: z.array(z.string()).optional(),
    /** For type=reference. The referenced table name (e.g. "sys_user"). */
    reference_table: z.string().optional(),
    /**
     * Which target-table column to write this variable's value into when
     * the producer is submitted. Undefined means the variable isn't mapped
     * (pure UI state, or mapped by a custom script).
     */
    map_to: z.string().optional(),
  })
  .refine(
    (v) => v.type !== "choice" || (v.choices && v.choices.length > 0),
    { message: "type=choice requires non-empty `choices`" }
  )
  .refine(
    (v) => v.type !== "reference" || !!v.reference_table,
    { message: "type=reference requires `reference_table`" }
  );

export const RecordProducerYamlSchema = z.object({
  name: z.string().min(1),
  table: z.string().min(1).describe("Target table the producer creates records in"),
  short_description: z.string().optional(),
  description: z.string().optional(),
  category: z.string().optional().describe("Catalog category sys_id"),
  submit_message: z
    .string()
    .optional()
    .describe("Message shown after submission"),
  variables: z.array(VariableSchema).min(1),
  /**
   * Optional raw-JS submit script hook. If set, runs after the auto-
   * generated map_to assignments — caller can layer custom logic.
   */
  extra_script: z.string().optional(),
});

export type RecordProducerYaml = z.infer<typeof RecordProducerYamlSchema>;
export type RecordProducerVariable = z.infer<typeof VariableSchema>;

export function parseRecordProducerYaml(content: string): RecordProducerYaml {
  let parsed: unknown;
  try {
    parsed = parseYaml(content);
  } catch (err) {
    throw new Error(
      `YAML parse error: ${err instanceof Error ? err.message : String(err)}`
    );
  }
  const result = RecordProducerYamlSchema.safeParse(parsed);
  if (!result.success) {
    const issues = result.error.issues
      .map((i) => `  - ${i.path.join(".") || "(root)"}: ${i.message}`)
      .join("\n");
    throw new Error(`Invalid record-producer spec:\n${issues}`);
  }
  return result.data;
}

export function loadRecordProducerYaml(path: string): RecordProducerYaml {
  return parseRecordProducerYaml(readFileSync(path, "utf-8"));
}

export function variableTypeCode(name: VariableTypeName): number {
  return VARIABLE_TYPES[name];
}

/**
 * Build the producer's submit script from `variables[].map_to`. Values
 * written to `current.*` fields; call this from the scaffolder.
 */
export function buildSubmitScript(spec: RecordProducerYaml): string {
  const lines: string[] = [
    "(function () {",
    "  // Generated by sn record-producer — maps form variables to target fields.",
  ];
  for (const v of spec.variables) {
    if (!v.map_to) continue;
    lines.push(
      `  if (producer.${v.name} !== undefined && producer.${v.name} !== '') current.${v.map_to} = producer.${v.name};`
    );
  }
  if (spec.extra_script) {
    lines.push("  // ——— extra_script below ———");
    lines.push(spec.extra_script);
  }
  lines.push("})();");
  return lines.join("\n");
}
