import { describe, it, expect } from "bun:test";
import { generateGo, snakeToPascal } from "../../src/utils/codegen-go.ts";
import type { DictEntry, ChoiceEntry } from "../../src/utils/codegen-ts.ts";
import type { CodegenData } from "../../src/utils/codegen-fetch.ts";

describe("snakeToPascal", () => {
  it("basic snake → Pascal", () => {
    expect(snakeToPascal("assigned_to")).toBe("AssignedTo");
    expect(snakeToPascal("number")).toBe("Number");
  });
  it("preserves ID/URL/IP acronyms", () => {
    expect(snakeToPascal("sys_id")).toBe("SysID");
    expect(snakeToPascal("http_url")).toBe("HTTPURL");
    expect(snakeToPascal("ip_address")).toBe("IPAddress");
  });
  it("handles mixed casing of input", () => {
    expect(snakeToPascal("User_Api_Key")).toBe("UserAPIKey");
  });
});

function minimal(): CodegenData {
  const dictionary: DictEntry[] = [
    {
      name: "incident",
      element: "number",
      column_label: "Number",
      internal_type: "string",
      max_length: "40",
      mandatory: "true",
    },
    {
      name: "incident",
      element: "state",
      column_label: "State",
      internal_type: "choice",
      mandatory: "true",
    },
    {
      name: "incident",
      element: "assigned_to",
      column_label: "Assigned to",
      internal_type: "reference",
      reference: "sys_user",
    },
    {
      name: "incident",
      element: "impact",
      column_label: "Impact",
      internal_type: "integer",
    },
    {
      name: "incident",
      element: "active",
      column_label: "Active",
      internal_type: "boolean",
    },
    {
      name: "incident",
      element: "opened_at",
      column_label: "Opened",
      internal_type: "glide_date_time",
    },
  ];
  const choices = new Map<string, ChoiceEntry[]>();
  choices.set("state", [
    { name: "incident", element: "state", value: "1", label: "New", inactive: "false" },
    { name: "incident", element: "state", value: "2", label: "In Progress", inactive: "false" },
    { name: "incident", element: "state", value: "7", label: "Closed", inactive: "false" },
  ]);

  return {
    table: "incident",
    tableLabel: "Incident",
    instanceUrl: "https://dev.example.com",
    dictionary,
    choices,
    ancestors: ["incident"],
  };
}

describe("generateGo", () => {
  it("emits package line and DO NOT EDIT header", () => {
    const out = generateGo(minimal());
    expect(out).toContain("// Code generated by");
    expect(out).toContain("package servicenow");
  });

  it("honours custom package name", () => {
    const out = generateGo(minimal(), { packageName: "snapi" });
    expect(out).toContain("package snapi");
  });

  it("emits choice type + const block", () => {
    const out = generateGo(minimal());
    expect(out).toContain("type IncidentState string");
    expect(out).toMatch(/IncidentStateNew\s+IncidentState = "1"/);
    expect(out).toMatch(/IncidentStateInProgress\s+IncidentState = "2"/);
    expect(out).toMatch(/IncidentStateClosed\s+IncidentState = "7"/);
  });

  it("uses choice type on struct field", () => {
    const out = generateGo(minimal());
    expect(out).toMatch(/State\s+IncidentState\s+`json:"state"`/);
  });

  it("maps int / float / bool / string correctly", () => {
    const out = generateGo(minimal());
    expect(out).toMatch(/Impact\s+int64\s+`json:"impact"`/);
    expect(out).toMatch(/Active\s+bool\s+`json:"active"`/);
    expect(out).toMatch(/OpenedAt\s+string\s+`json:"opened_at"`/);
  });

  it("annotates reference with target table", () => {
    const out = generateGo(minimal());
    expect(out).toContain("References sys_user.sys_id");
    expect(out).toMatch(/AssignedTo\s+string\s+`json:"assigned_to"`/);
  });

  it("emits struct name PascalCased", () => {
    const out = generateGo(minimal());
    expect(out).toContain("type Incident struct {");
  });

  it("preserves acronyms in Go field names", () => {
    const input = minimal();
    input.dictionary.push({
      name: "incident",
      element: "sys_id",
      column_label: "Sys ID",
      internal_type: "GUID",
    });
    const out = generateGo(input);
    expect(out).toMatch(/SysID\s+string\s+`json:"sys_id"`/);
  });

  it("skips system fields when includeSystem=false", () => {
    const input = minimal();
    input.dictionary.push({
      name: "incident",
      element: "sys_id",
      column_label: "Sys ID",
      internal_type: "GUID",
    });
    const out = generateGo(input, { includeSystem: false });
    expect(out).not.toMatch(/SysID\s+string\s+`json:"sys_id"`/);
  });

  it("prefixes digit-start const names with V", () => {
    const input = minimal();
    input.choices.set("priority", [
      { name: "incident", element: "priority", value: "1", label: "1 - Critical", inactive: "false" },
    ]);
    input.dictionary.push({
      name: "incident",
      element: "priority",
      column_label: "Priority",
      internal_type: "choice",
    });
    const out = generateGo(input);
    // label starts with "1" → const name suffix must not start with digit
    expect(out).toMatch(/IncidentPriorityV1Critical/);
  });
});
